# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

group("gn_all") {
  testonly = true

  deps = [ ":tests", ]

  deps += [
    # Place your deps tree to your code here
    # so that GN knows about it!
  ]
}

group("tests") {
  testonly = true

  deps = [
    "//src/test/:hello_all",
  ]

  if (is_win) {
    if (is_clang) {
      deps += [
        "//src/test/defapp/:defapp(//build/toolchain/win:clang_x64)",
        "//src/test/defapp/:defapp(//build/toolchain/win:clang_x86)",
      ]
    } else {
      deps += [
        "//src/test/defapp/:defapp(//build/toolchain/win:x64)",
        "//src/test/defapp/:defapp(//build/toolchain/win:x86)",
      ]
    }
  }
}
